"use client";

import { useState } from "react";
import { toast } from "sonner";
import { AlertCircle, CheckCircle2, Clock3, History, Loader2, Search, ShieldCheck, UserRound, X, ExternalLink } from "lucide-react";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";

type User = { id: string; name: string; username: string | null; email?: string | null; phone?: string | null; role: string; roleLabel: string; status: string; kycStatus: string; createdAt: string };
type Detail = User & { firstName: string | null; lastName: string | null; avatar: string | null; country: string | null; city: string | null; address: string | null; nationality: string | null; gender: string | null; birthDate: string | null; occupation: string | null; kycSubmittedAt: string | null; kycVerifiedAt: string | null; idType: string | null; idNumber: string | null; idCountry: string | null; idExpiryDate: string | null; wallets: { currency: string; balance: number; frozenBalance: number }[]; _count: { transactionsFrom: number; transactionsTo: number; referrals: number; sessions: number }; displayName: string };
type Log = { id: string; targetId: string | null; details: string | null; status: string; createdAt: string };

const formatDate = (value: string) => new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));

export function AgentsHubClient() {
  const [query, setQuery] = useState(""); const [users, setUsers] = useState<User[]>([]); const [searched, setSearched] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const [selected, setSelected] = useState<User | null>(null); const [detail, setDetail] = useState<Detail | null>(null); const [detailLoading, setDetailLoading] = useState(false); const [newRole, setNewRole] = useState<"AGENT" | "SUPERVISEUR" | "">(""); const [saving, setSaving] = useState(false);
  const [logs, setLogs] = useState<Log[]>([]); const [showLogs, setShowLogs] = useState(false); const [kycViewer, setKycViewer] = useState<{ url: string; label: string } | null>(null);

  async function searchUsers(event: React.FormEvent) { event.preventDefault(); if (!query.trim()) return setError("Saisissez un username, un ID, un téléphone ou un email."); setLoading(true); setError(""); setSearched(true); try { const r = await fetch(`/api/supervisor/user-search?q=${encodeURIComponent(query.trim())}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setUsers(d.users); } catch (e) { setError(e instanceof Error ? e.message : "Recherche impossible."); setUsers([]); } finally { setLoading(false); } }
  async function openUser(user: User) { setSelected(user); setNewRole(""); setDetail(null); setDetailLoading(true); try { const r = await fetch(`/api/supervisor/user-details?userId=${encodeURIComponent(user.id)}`, { cache: "no-store" }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setDetail(d.user); } catch (e) { toast.error(e instanceof Error ? e.message : "Détails indisponibles."); } finally { setDetailLoading(false); } }
  async function changeRole() { if (!selected || !newRole) return; setSaving(true); try { const r = await fetch("/api/supervisor/user-role", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId: selected.id, newRole }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setUsers((items) => items.map((i) => i.id === selected.id ? { ...i, role: d.user.role, roleLabel: d.user.roleLabel } : i)); setSelected({ ...selected, role: d.user.role, roleLabel: d.user.roleLabel }); setDetail((v) => v ? { ...v, role: d.user.role, roleLabel: d.user.roleLabel } : v); setNewRole(""); toast.success("Rôle mis à jour"); } catch (e) { toast.error(e instanceof Error ? e.message : "Modification impossible."); } finally { setSaving(false); } }
  async function loadLogs() { const r = await fetch("/api/supervisor/audit-log", { cache: "no-store" }); const d = await r.json(); setLogs(d.logs || []); setShowLogs(true); }
  const canEdit = (u: User) => ["USER", "AGENT", "SUPERVISEUR"].includes(u.role);
  return <main className="min-h-screen bg-slate-950 px-3 py-5 text-slate-100 sm:px-6 sm:py-8 lg:px-8"><div className="mx-auto flex w-full max-w-7xl flex-col gap-6 lg:gap-8">
    <header className="flex flex-col gap-5 rounded-3xl border border-blue-900/50 bg-blue-950/40 p-6 shadow-2xl shadow-blue-950/20 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="rounded-2xl bg-blue-500/15 p-3 text-blue-300"><ShieldCheck className="size-7" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-amber-300">PiMobiPay · Supervision</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Hub des Agents</h1><p className="mt-2 text-sm text-blue-100/70">Recherchez un utilisateur, consultez ses détails et gérez son rôle.</p></div></div><Button variant="outline" className="border-blue-700 bg-blue-950/50 text-blue-100 hover:bg-blue-900" onClick={loadLogs}><History data-icon="inline-start" /> Mes actions</Button></header>
    <Card className="border-blue-900/60 bg-slate-900/80 text-slate-100"><CardHeader><CardTitle className="text-xl">Rechercher un utilisateur</CardTitle><CardDescription className="text-slate-400">Username, ID, téléphone ou email. Cliquez sur un résultat pour voir son profil complet.</CardDescription></CardHeader><CardContent><form onSubmit={searchUsers} className="flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3 size-5 text-blue-300" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Rechercher un utilisateur..." className="h-11 border-blue-900 bg-slate-950 pl-10 text-slate-100 placeholder:text-slate-500" /></div><Button type="submit" className="h-11 bg-blue-600 hover:bg-blue-500" disabled={loading}>{loading ? <Loader2 className="animate-spin" data-icon="inline-start" /> : <Search data-icon="inline-start" />} Rechercher</Button></form></CardContent></Card>
    {error && <Alert variant="destructive"><AlertCircle data-icon="inline-start" /><AlertDescription>{error}</AlertDescription></Alert>}
    {!searched && !error && <div className="flex flex-col items-center gap-3 rounded-3xl border border-dashed border-blue-900 bg-slate-900/50 px-6 py-16 text-center"><Search className="size-10 text-blue-400" /><p className="font-medium">Recherchez un utilisateur pour commencer.</p></div>}
    {searched && !loading && users.length === 0 && !error && <div className="rounded-3xl border border-blue-900 bg-slate-900/50 p-8 text-center text-slate-400">Aucun utilisateur ne correspond à cette recherche.</div>}
    <div className="flex flex-col gap-4">{users.map((user) => <Card key={user.id} className="border-blue-900/60 bg-slate-900 text-slate-100"><CardContent className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:justify-between"><button className="flex items-start gap-4 text-left" onClick={() => openUser(user)}><div className="rounded-full bg-blue-500/15 p-3 text-blue-300"><UserRound className="size-6" /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold">{user.name}</h2><Badge variant="outline" className="border-emerald-500/40 text-emerald-300">{user.status === "ACTIVE" ? "Actif" : user.status}</Badge></div><p className="mt-1 text-sm text-blue-200">{user.username ? `@${user.username}` : user.email || "Utilisateur"}</p><div className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-xs text-slate-400"><span>ID: {user.id}</span><span>Rôle: <strong className="text-amber-200">{user.roleLabel}</strong></span><span>KYC: {user.kycStatus}</span></div></div></button><Button variant="outline" className="border-blue-800 text-blue-200 hover:bg-blue-900" onClick={() => openUser(user)}>Voir les détails</Button></CardContent></Card>)}</div>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[90vh] overflow-y-auto border-blue-900 bg-slate-900 text-slate-100"><DialogHeader><DialogTitle>Détails de l&apos;utilisateur</DialogTitle><DialogDescription className="text-slate-400">Informations du compte et gestion des rôles autorisés.</DialogDescription></DialogHeader>{detailLoading ? <div className="flex justify-center py-12"><Loader2 className="animate-spin text-blue-400" /></div> : detail && <div className="flex flex-col gap-5"><div className="grid gap-3 rounded-2xl bg-slate-950 p-4 sm:grid-cols-2"><Info label="Nom" value={detail.displayName} /><Info label="Username" value={detail.username ? `@${detail.username}` : null} /><Info label="Email" value={detail.email} /><Info label="Téléphone" value={detail.phone} /><Info label="Localisation" value={[detail.city, detail.country].filter(Boolean).join(", ")} /><Info label="Inscription" value={formatDate(detail.createdAt)} /><Info label="Rôle actuel" value={detail.roleLabel} /><Info label="KYC" value={detail.kycStatus} /></div><div className="grid grid-cols-1 gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Transactions" value={String(detail._count.transactionsFrom + detail._count.transactionsTo)} /><Info label="Parrainages" value={String(detail._count.referrals)} /><Info label="Sessions" value={String(detail._count.sessions)} /><Info label="Profession" value={detail.occupation} /></div>{canEdit(detail) && <div className="rounded-2xl border border-blue-900 bg-blue-950/30 p-4"><p className="mb-3 text-sm font-semibold">Changer le rôle</p><ToggleGroup type="single" value={newRole} onValueChange={(v) => setNewRole(v as typeof newRole)} className="justify-start"><ToggleGroupItem value="AGENT">AGENT</ToggleGroupItem><ToggleGroupItem value="SUPERVISEUR">SUPERVISEUR</ToggleGroupItem></ToggleGroup><Button className="mt-4 bg-amber-400 text-slate-950 hover:bg-amber-300" disabled={!newRole || saving} onClick={changeRole}>{saving ? <Loader2 className="animate-spin" data-icon="inline-start" /> : <CheckCircle2 data-icon="inline-start" />} Enregistrer le rôle</Button></div>}</div>}<DialogFooter><Button variant="outline" onClick={() => setSelected(null)}>Fermer</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(kycViewer)} onOpenChange={(open) => !open && setKycViewer(null)}><DialogContent className="w-[calc(100%-1.5rem)] max-w-6xl border-blue-900 bg-slate-950 text-slate-100 sm:w-[calc(100%-3rem)]"><DialogHeader><DialogTitle>{kycViewer?.label}</DialogTitle></DialogHeader>{kycViewer && <div className="flex max-h-[70vh] items-center justify-center overflow-auto rounded-2xl bg-black p-2"><img src={kycViewer.url} alt={kycViewer.label} className="max-h-[65vh] max-w-full object-contain" /></div>}</DialogContent></Dialog>
    <Dialog open={showLogs} onOpenChange={setShowLogs}><DialogContent className="border-blue-900 bg-slate-900 text-slate-100"><DialogHeader><DialogTitle>Mes changements de rôle</DialogTitle><DialogDescription className="text-slate-400">Historique en lecture seule.</DialogDescription></DialogHeader><div className="flex max-h-80 flex-col gap-3 overflow-y-auto">{logs.length ? logs.map((log) => <div key={log.id} className="rounded-xl border border-blue-900 bg-slate-950 p-3 text-xs"><div className="flex items-center gap-2 text-emerald-300"><Clock3 className="size-4" />{formatDate(log.createdAt)}</div><p className="mt-2 text-slate-300">Utilisateur: {log.targetId}</p><p className="mt-1 text-slate-500">{log.details}</p></div>) : <p className="text-sm text-slate-500">Aucun changement enregistré.</p>}</div></DialogContent></Dialog>
  </div></main>;
}
function Info({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 break-words text-sm font-medium text-slate-100">{value || "—"}</p></div>; }

// KYC preview is kept as a reusable accessible viewer for cards on supervisor surfaces.
export function KycDocumentButton({ url, label, onOpen }: { url?: string | null; label: string; onOpen: (url: string, label: string) => void }) { return url ? <Button variant="outline" size="sm" onClick={() => onOpen(url, label)}><ExternalLink data-icon="inline-start" /> {label}</Button> : <span className="text-xs text-slate-500">{label} indisponible</span>; }
