"use client"

import Link from "next/link"
import { ArrowDownToLine, ArrowUpRight, CheckCircle2, Copy, Download, MoreHorizontal, Plus, QrCode, Store, TrendingUp, Wallet } from "lucide-react"
import { useState } from "react"

const transactions = [
  { name: "Paiement reçu", ref: "PMB-829104", date: "Aujourd'hui, 14:32", amount: "+ 85 000 XAF", status: "Réussi" },
  { name: "Paiement reçu", ref: "PMB-829088", date: "Aujourd'hui, 12:08", amount: "+ 42 500 XAF", status: "Réussi" },
  { name: "Retrait vers wallet", ref: "WAL-441209", date: "Hier, 18:45", amount: "− 120 000 XAF", status: "En cours" },
  { name: "Paiement reçu", ref: "PMB-828741", date: "Hier, 16:21", amount: "+ 18 000 XAF", status: "Réussi" },
]

function Stat({ label, value, note, icon: Icon, accent = "blue" }: { label: string; value: string; note: string; icon: typeof Wallet; accent?: "blue" | "gold" }) {
  return <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-white/50">{label}</p><p className="mt-3 text-2xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-white/40">{note}</p></div><span className={accent === "gold" ? "rounded-xl bg-amber-300/10 p-3 text-amber-200" : "rounded-xl bg-blue-500/10 p-3 text-blue-300"}><Icon className="size-5" /></span></div></div>
}

export default function MerchantPage() {
  const [copied, setCopied] = useState(false)
  const copyCode = async () => { await navigator.clipboard?.writeText("PMB-MARCHAND-001"); setCopied(true); window.setTimeout(() => setCopied(false), 1600) }
  return <div className="flex flex-col gap-8">
    <section className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm text-blue-300">Tableau de bord</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-balance">Gérez votre activité en toute simplicité.</h1><p className="mt-2 max-w-xl text-sm leading-6 text-white/50">Suivez vos encaissements, partagez votre QR et gardez le contrôle de votre boutique.</p></div><div className="flex gap-3"><Link href="/merchant/payments" className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 text-sm font-medium shadow-lg shadow-blue-600/20 hover:bg-blue-500"><QrCode className="size-4" />Encaisser</Link><Link href="/merchant/balance" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-4 py-3 text-sm text-white/75 hover:bg-white/5"><ArrowDownToLine className="size-4" />Retirer</Link></div></section>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Solde disponible" value="1 248 500 XAF" note="Mis à jour à l'instant" icon={Wallet} accent="gold" /><Stat label="Total encaissé" value="3 842 000 XAF" note="+12,8% ce mois-ci" icon={TrendingUp} /><Stat label="Transactions" value="248" note="+24 aujourd'hui" icon={ArrowUpRight} /><Stat label="Retraits en cours" value="1" note="120 000 XAF en traitement" icon={ArrowDownToLine} /></section>
    <section className="grid gap-5 xl:grid-cols-[1.4fr_0.6fr]"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-6"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Activité récente</h2><p className="mt-1 text-sm text-white/45">Vos dernières opérations</p></div><Link href="/merchant/transactions" className="text-sm text-blue-300 hover:text-blue-200">Voir tout</Link></div><div className="mt-6 flex flex-col gap-1">{transactions.map((transaction) => <div key={transaction.ref} className="flex items-center gap-3 rounded-xl px-2 py-4 hover:bg-white/[0.03]"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-500/10 text-blue-300"><ArrowUpRight className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{transaction.name}</p><p className="mt-1 text-xs text-white/40">{transaction.ref} · {transaction.date}</p></div><div className="text-right"><p className="text-sm font-medium">{transaction.amount}</p><p className={transaction.status === "Réussi" ? "mt-1 text-xs text-emerald-300" : "mt-1 text-xs text-amber-200"}>{transaction.status}</p></div><MoreHorizontal className="size-4 text-white/30" /></div>)}</div></div><div className="rounded-2xl border border-blue-400/20 bg-gradient-to-br from-blue-600/20 to-blue-900/10 p-6"><div className="flex items-center justify-between"><div><p className="text-sm text-blue-200">Votre QR marchand</p><h2 className="mt-2 text-xl font-semibold">Recevez des paiements</h2></div><span className="rounded-xl bg-white/10 p-3"><QrCode className="size-6" /></span></div><div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-white/45">Identifiant marchand</p><div className="mt-2 flex items-center justify-between gap-3"><code className="text-sm text-white/80">PMB-MARCHAND-001</code><button onClick={copyCode} className="text-blue-200" aria-label="Copier l'identifiant">{copied ? <CheckCircle2 className="size-4" /> : <Copy className="size-4" />}</button></div></div><Link href="/merchant/payments" className="mt-5 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-medium text-blue-950 hover:bg-blue-50"><QrCode className="size-4" />Afficher mon QR</Link></div></section>
    <section className="grid gap-5 md:grid-cols-3"><Link href="/merchant/payments" className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 transition hover:border-blue-400/40"><Plus className="size-5 text-blue-300" /><h3 className="mt-4 font-medium">Créer une demande</h3><p className="mt-2 text-sm leading-6 text-white/45">Générez une demande de paiement avec un montant précis.</p></Link><Link href="/merchant/reports" className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 transition hover:border-blue-400/40"><Download className="size-5 text-amber-200" /><h3 className="mt-4 font-medium">Exporter un rapport</h3><p className="mt-2 text-sm leading-6 text-white/45">Analysez vos encaissements et transactions par période.</p></Link><Link href="/merchant/profile" className="rounded-2xl border border-white/10 bg-white/[0.035] p-5 transition hover:border-blue-400/40"><Store className="size-5 text-blue-300" /><h3 className="mt-4 font-medium">Ma boutique</h3><p className="mt-2 text-sm leading-6 text-white/45">Mettez à jour vos informations et votre profil marchand.</p></Link></section>
  </div>
}
