export interface Country {
  code: string
  name: string
  dialCode: string
  flag: string
  currency: string
  currencySymbol: string
  piToLocalRate: number
  mobileMoneyOperators: string[]
}

export const countries: Country[] = [
  {
    code: "AF",
    name: "Afghanistan",
    dialCode: "+93",
    flag: "🇦🇫",
    currency: "AFN",
    currencySymbol: "؋",
    piToLocalRate: 70.5,
    mobileMoneyOperators: ["Roshan", "Etisalat", "MTN"],
  },
  {
    code: "AL",
    name: "Albania",
    dialCode: "+355",
    flag: "🇦🇱",
    currency: "ALL",
    currencySymbol: "L",
    piToLocalRate: 92.8,
    mobileMoneyOperators: ["Vodafone", "ALBtelecom", "One"],
  },
  {
    code: "DZ",
    name: "Algeria",
    dialCode: "+213",
    flag: "🇩🇿",
    currency: "DZD",
    currencySymbol: "د.ج",
    piToLocalRate: 135.2,
    mobileMoneyOperators: ["Mobilis", "Djezzy", "Ooredoo"],
  },
  {
    code: "AO",
    name: "Angola",
    dialCode: "+244",
    flag: "🇦🇴",
    currency: "AOA",
    currencySymbol: "Kz",
    piToLocalRate: 920.0,
    mobileMoneyOperators: ["Unitel Money", "Multicaixa", "Zap"],
  },
  {
    code: "AR",
    name: "Argentina",
    dialCode: "+54",
    flag: "🇦🇷",
    currency: "ARS",
    currencySymbol: "$",
    piToLocalRate: 1025.0,
    mobileMoneyOperators: ["Personal Pay", "Claro Pay", "Movistar Wallet"],
  },
  {
    code: "AM",
    name: "Armenia",
    dialCode: "+374",
    flag: "🇦🇲",
    currency: "AMD",
    currencySymbol: "֏",
    piToLocalRate: 387.5,
    mobileMoneyOperators: ["Beeline", "Ucom", "Viva"],
  },
  {
    code: "AU",
    name: "Australia",
    dialCode: "+61",
    flag: "🇦🇺",
    currency: "AUD",
    currencySymbol: "$",
    piToLocalRate: 1.58,
    mobileMoneyOperators: ["Telstra", "Optus", "Vodafone"],
  },
  {
    code: "AT",
    name: "Austria",
    dialCode: "+43",
    flag: "🇦🇹",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["A1", "Magenta", "Drei"],
  },
  {
    code: "AZ",
    name: "Azerbaijan",
    dialCode: "+994",
    flag: "🇦🇿",
    currency: "AZN",
    currencySymbol: "₼",
    piToLocalRate: 1.7,
    mobileMoneyOperators: ["Azercell", "Bakcell", "Nar"],
  },
  {
    code: "BD",
    name: "Bangladesh",
    dialCode: "+880",
    flag: "🇧🇩",
    currency: "BDT",
    currencySymbol: "৳",
    piToLocalRate: 119.5,
    mobileMoneyOperators: ["bKash", "Nagad", "Rocket"],
  },
  {
    code: "BE",
    name: "Belgium",
    dialCode: "+32",
    flag: "🇧🇪",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["Proximus", "Orange", "Base"],
  },
  {
    code: "BJ",
    name: "Benin",
    dialCode: "+229",
    flag: "🇧🇯",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["MTN Mobile Money", "Moov Money", "Celtiis"],
  },
  {
    code: "BO",
    name: "Bolivia",
    dialCode: "+591",
    flag: "🇧🇴",
    currency: "BOB",
    currencySymbol: "Bs.",
    piToLocalRate: 6.91,
    mobileMoneyOperators: ["Tigo Money", "Entel", "Viva"],
  },
  {
    code: "BR",
    name: "Brazil",
    dialCode: "+55",
    flag: "🇧🇷",
    currency: "BRL",
    currencySymbol: "R$",
    piToLocalRate: 5.65,
    mobileMoneyOperators: ["Vivo Pay", "Claro Pay", "TIM"],
  },
  {
    code: "BF",
    name: "Burkina Faso",
    dialCode: "+226",
    flag: "🇧🇫",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Orange Money", "Moov Money", "Coris Money"],
  },
  {
    code: "BI",
    name: "Burundi",
    dialCode: "+257",
    flag: "🇧🇮",
    currency: "BIF",
    currencySymbol: "FBu",
    piToLocalRate: 2890.0,
    mobileMoneyOperators: ["Ecocash", "Lumicash", "Smart Money"],
  },
  {
    code: "CM",
    name: "Cameroon",
    dialCode: "+237",
    flag: "🇨🇲",
    currency: "XAF",
    currencySymbol: "FCFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Orange Money", "MTN Mobile Money", "Express Union"],
  },
  {
    code: "CA",
    name: "Canada",
    dialCode: "+1",
    flag: "🇨🇦",
    currency: "CAD",
    currencySymbol: "$",
    piToLocalRate: 1.43,
    mobileMoneyOperators: ["Rogers", "Bell", "Telus"],
  },
  {
    code: "TD",
    name: "Chad",
    dialCode: "+235",
    flag: "🇹🇩",
    currency: "XAF",
    currencySymbol: "FCFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Airtel Money", "Tigo Cash", "Moov Money"],
  },
  {
    code: "CL",
    name: "Chile",
    dialCode: "+56",
    flag: "🇨🇱",
    currency: "CLP",
    currencySymbol: "$",
    piToLocalRate: 985.0,
    mobileMoneyOperators: ["Entel", "Movistar", "Claro"],
  },
  {
    code: "CN",
    name: "China",
    dialCode: "+86",
    flag: "🇨🇳",
    currency: "CNY",
    currencySymbol: "¥",
    piToLocalRate: 7.25,
    mobileMoneyOperators: ["WeChat Pay", "Alipay", "China Mobile"],
  },
  {
    code: "CO",
    name: "Colombia",
    dialCode: "+57",
    flag: "🇨🇴",
    currency: "COP",
    currencySymbol: "$",
    piToLocalRate: 4250.0,
    mobileMoneyOperators: ["Nequi", "Daviplata", "Movii"],
  },
  {
    code: "CG",
    name: "Congo",
    dialCode: "+242",
    flag: "🇨🇬",
    currency: "XAF",
    currencySymbol: "FCFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Airtel Money", "MTN Mobile Money", "Azur"],
  },
  {
    code: "CD",
    name: "Congo (DRC)",
    dialCode: "+243",
    flag: "🇨🇩",
    currency: "CDF",
    currencySymbol: "FC",
    piToLocalRate: 2850.0,
    mobileMoneyOperators: ["M-Pesa", "Orange Money", "Airtel Money"],
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    dialCode: "+225",
    flag: "🇨🇮",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Orange Money", "MTN Mobile Money", "Moov Money"],
  },
  {
    code: "EG",
    name: "Egypt",
    dialCode: "+20",
    flag: "🇪🇬",
    currency: "EGP",
    currencySymbol: "£",
    piToLocalRate: 50.8,
    mobileMoneyOperators: ["Vodafone Cash", "Orange Cash", "Etisalat Cash"],
  },
  {
    code: "ET",
    name: "Ethiopia",
    dialCode: "+251",
    flag: "🇪🇹",
    currency: "ETB",
    currencySymbol: "Br",
    piToLocalRate: 125.0,
    mobileMoneyOperators: ["M-Birr", "HelloCash", "Amole"],
  },
  {
    code: "FR",
    name: "France",
    dialCode: "+33",
    flag: "🇫🇷",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["Orange", "SFR", "Bouygues"],
  },
  {
    code: "GA",
    name: "Gabon",
    dialCode: "+241",
    flag: "🇬🇦",
    currency: "XAF",
    currencySymbol: "FCFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Airtel Money", "Moov Money", "Libertis"],
  },
  {
    code: "GM",
    name: "Gambia",
    dialCode: "+220",
    flag: "🇬🇲",
    currency: "GMD",
    currencySymbol: "D",
    piToLocalRate: 68.5,
    mobileMoneyOperators: ["Africell Money", "QMoney", "Comium"],
  },
  {
    code: "DE",
    name: "Germany",
    dialCode: "+49",
    flag: "🇩🇪",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["Telekom", "Vodafone", "O2"],
  },
  {
    code: "GH",
    name: "Ghana",
    dialCode: "+233",
    flag: "🇬🇭",
    currency: "GHS",
    currencySymbol: "₵",
    piToLocalRate: 15.8,
    mobileMoneyOperators: ["MTN Mobile Money", "Vodafone Cash", "AirtelTigo Money"],
  },
  {
    code: "GR",
    name: "Greece",
    dialCode: "+30",
    flag: "🇬🇷",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["Cosmote", "Vodafone", "Wind"],
  },
  {
    code: "GN",
    name: "Guinea",
    dialCode: "+224",
    flag: "🇬🇳",
    currency: "GNF",
    currencySymbol: "FG",
    piToLocalRate: 8650.0,
    mobileMoneyOperators: ["Orange Money", "MTN Mobile Money", "Cellcom"],
  },
  {
    code: "HT",
    name: "Haiti",
    dialCode: "+509",
    flag: "🇭🇹",
    currency: "HTG",
    currencySymbol: "G",
    piToLocalRate: 132.5,
    mobileMoneyOperators: ["MonCash", "Natcash", "TchoTcho Mobile"],
  },
  {
    code: "IN",
    name: "India",
    dialCode: "+91",
    flag: "🇮🇳",
    currency: "INR",
    currencySymbol: "₹",
    piToLocalRate: 84.2,
    mobileMoneyOperators: ["Paytm", "PhonePe", "Google Pay"],
  },
  {
    code: "ID",
    name: "Indonesia",
    dialCode: "+62",
    flag: "🇮🇩",
    currency: "IDR",
    currencySymbol: "Rp",
    piToLocalRate: 16100.0,
    mobileMoneyOperators: ["GoPay", "OVO", "Dana"],
  },
  {
    code: "IT",
    name: "Italy",
    dialCode: "+39",
    flag: "🇮🇹",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["TIM", "Vodafone", "Wind Tre"],
  },
  {
    code: "JP",
    name: "Japan",
    dialCode: "+81",
    flag: "🇯🇵",
    currency: "JPY",
    currencySymbol: "¥",
    piToLocalRate: 151.0,
    mobileMoneyOperators: ["NTT Docomo", "au", "SoftBank"],
  },
  {
    code: "KE",
    name: "Kenya",
    dialCode: "+254",
    flag: "🇰🇪",
    currency: "KES",
    currencySymbol: "KSh",
    piToLocalRate: 130.5,
    mobileMoneyOperators: ["M-Pesa", "Airtel Money", "T-Kash"],
  },
  {
    code: "KR",
    name: "South Korea",
    dialCode: "+82",
    flag: "🇰🇷",
    currency: "KRW",
    currencySymbol: "₩",
    piToLocalRate: 1385.0,
    mobileMoneyOperators: ["KakaoPay", "Naver Pay", "Toss"],
  },
  {
    code: "LR",
    name: "Liberia",
    dialCode: "+231",
    flag: "🇱🇷",
    currency: "LRD",
    currencySymbol: "$",
    piToLocalRate: 195.0,
    mobileMoneyOperators: ["Orange Money", "Lonestar Cell MTN", "Novafone"],
  },
  {
    code: "MG",
    name: "Madagascar",
    dialCode: "+261",
    flag: "🇲🇬",
    currency: "MGA",
    currencySymbol: "Ar",
    piToLocalRate: 4580.0,
    mobileMoneyOperators: ["Orange Money", "Airtel Money", "Telma Mobile Money"],
  },
  {
    code: "MW",
    name: "Malawi",
    dialCode: "+265",
    flag: "🇲🇼",
    currency: "MWK",
    currencySymbol: "MK",
    piToLocalRate: 1750.0,
    mobileMoneyOperators: ["Airtel Money", "TNM Mpamba", "NBS Bank"],
  },
  {
    code: "ML",
    name: "Mali",
    dialCode: "+223",
    flag: "🇲🇱",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Orange Money", "Moov Money", "Malitel"],
  },
  {
    code: "MX",
    name: "Mexico",
    dialCode: "+52",
    flag: "🇲🇽",
    currency: "MXN",
    currencySymbol: "$",
    piToLocalRate: 18.2,
    mobileMoneyOperators: ["Telcel", "Movistar", "AT&T"],
  },
  {
    code: "MA",
    name: "Morocco",
    dialCode: "+212",
    flag: "🇲🇦",
    currency: "MAD",
    currencySymbol: "د.م.",
    piToLocalRate: 10.15,
    mobileMoneyOperators: ["Orange Money", "Maroc Telecom", "Inwi Money"],
  },
  {
    code: "MZ",
    name: "Mozambique",
    dialCode: "+258",
    flag: "🇲🇿",
    currency: "MZN",
    currencySymbol: "MT",
    piToLocalRate: 63.9,
    mobileMoneyOperators: ["M-Pesa", "Mkesh", "e-Mola"],
  },
  {
    code: "NE",
    name: "Niger",
    dialCode: "+227",
    flag: "🇳🇪",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Orange Money", "Moov Money", "Airtel Money"],
  },
  {
    code: "NG",
    name: "Nigeria",
    dialCode: "+234",
    flag: "🇳🇬",
    currency: "NGN",
    currencySymbol: "₦",
    piToLocalRate: 1580.0,
    mobileMoneyOperators: ["OPay", "PalmPay", "Paga"],
  },
  {
    code: "PK",
    name: "Pakistan",
    dialCode: "+92",
    flag: "🇵🇰",
    currency: "PKR",
    currencySymbol: "₨",
    piToLocalRate: 280.0,
    mobileMoneyOperators: ["JazzCash", "Easypaisa", "UPaisa"],
  },
  {
    code: "PE",
    name: "Peru",
    dialCode: "+51",
    flag: "🇵🇪",
    currency: "PEN",
    currencySymbol: "S/",
    piToLocalRate: 3.78,
    mobileMoneyOperators: ["Yape", "Plin", "Tunki"],
  },
  {
    code: "PH",
    name: "Philippines",
    dialCode: "+63",
    flag: "🇵🇭",
    currency: "PHP",
    currencySymbol: "₱",
    piToLocalRate: 58.5,
    mobileMoneyOperators: ["GCash", "PayMaya", "Coins.ph"],
  },
  {
    code: "PL",
    name: "Poland",
    dialCode: "+48",
    flag: "🇵🇱",
    currency: "PLN",
    currencySymbol: "zł",
    piToLocalRate: 4.05,
    mobileMoneyOperators: ["Orange", "Play", "T-Mobile"],
  },
  {
    code: "RW",
    name: "Rwanda",
    dialCode: "+250",
    flag: "🇷🇼",
    currency: "RWF",
    currencySymbol: "FRw",
    piToLocalRate: 1390.0,
    mobileMoneyOperators: ["MTN Mobile Money", "Airtel Money", "Tigo Cash"],
  },
  {
    code: "SN",
    name: "Senegal",
    dialCode: "+221",
    flag: "🇸🇳",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Orange Money", "Free Money", "Wave"],
  },
  {
    code: "ZA",
    name: "South Africa",
    dialCode: "+27",
    flag: "🇿🇦",
    currency: "ZAR",
    currencySymbol: "R",
    piToLocalRate: 18.5,
    mobileMoneyOperators: ["Vodacom", "MTN", "Cell C"],
  },
  {
    code: "ES",
    name: "Spain",
    dialCode: "+34",
    flag: "🇪🇸",
    currency: "EUR",
    currencySymbol: "€",
    piToLocalRate: 0.95,
    mobileMoneyOperators: ["Movistar", "Orange", "Vodafone"],
  },
  {
    code: "LK",
    name: "Sri Lanka",
    dialCode: "+94",
    flag: "🇱🇰",
    currency: "LKR",
    currencySymbol: "Rs",
    piToLocalRate: 295.0,
    mobileMoneyOperators: ["Dialog eZ Cash", "Mobitel mCash", "Airtel"],
  },
  {
    code: "TZ",
    name: "Tanzania",
    dialCode: "+255",
    flag: "🇹🇿",
    currency: "TZS",
    currencySymbol: "TSh",
    piToLocalRate: 2550.0,
    mobileMoneyOperators: ["M-Pesa", "Tigo Pesa", "Airtel Money"],
  },
  {
    code: "TH",
    name: "Thailand",
    dialCode: "+66",
    flag: "🇹🇭",
    currency: "THB",
    currencySymbol: "฿",
    piToLocalRate: 36.2,
    mobileMoneyOperators: ["TrueMoney", "AIS", "dtac"],
  },
  {
    code: "TG",
    name: "Togo",
    dialCode: "+228",
    flag: "🇹🇬",
    currency: "XOF",
    currencySymbol: "CFA",
    piToLocalRate: 615.0,
    mobileMoneyOperators: ["Flooz", "TMoney", "Moov Money"],
  },
  {
    code: "TR",
    name: "Turkey",
    dialCode: "+90",
    flag: "🇹🇷",
    currency: "TRY",
    currencySymbol: "₺",
    piToLocalRate: 35.2,
    mobileMoneyOperators: ["Turkcell", "Vodafone", "Turk Telekom"],
  },
  {
    code: "UG",
    name: "Uganda",
    dialCode: "+256",
    flag: "🇺🇬",
    currency: "UGX",
    currencySymbol: "USh",
    piToLocalRate: 3780.0,
    mobileMoneyOperators: ["MTN Mobile Money", "Airtel Money", "Chipper Cash"],
  },
  {
    code: "GB",
    name: "United Kingdom",
    dialCode: "+44",
    flag: "🇬🇧",
    currency: "GBP",
    currencySymbol: "£",
    piToLocalRate: 0.8,
    mobileMoneyOperators: ["EE", "Vodafone", "O2"],
  },
  {
    code: "US",
    name: "United States",
    dialCode: "+1",
    flag: "🇺🇸",
    currency: "USD",
    currencySymbol: "$",
    piToLocalRate: 1.0,
    mobileMoneyOperators: ["Verizon", "AT&T", "T-Mobile"],
  },
  {
    code: "VN",
    name: "Vietnam",
    dialCode: "+84",
    flag: "🇻🇳",
    currency: "VND",
    currencySymbol: "₫",
    piToLocalRate: 25500.0,
    mobileMoneyOperators: ["MoMo", "ZaloPay", "ViettelPay"],
  },
  {
    code: "ZM",
    name: "Zambia",
    dialCode: "+260",
    flag: "🇿🇲",
    currency: "ZMW",
    currencySymbol: "ZK",
    piToLocalRate: 27.2,
    mobileMoneyOperators: ["MTN Mobile Money", "Airtel Money", "Zamtel Kwacha"],
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    dialCode: "+263",
    flag: "🇿🇼",
    currency: "USD",
    currencySymbol: "$",
    piToLocalRate: 1.0,
    mobileMoneyOperators: ["EcoCash", "OneMoney", "Telecash"],
  },
]
